export const moviesReducer = (
  state = [
    {
      _id: "m1",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "Spiral 2021",
      type: "movie",
      imgUrl: "/images/m1.jpg",
      imdbRate: "5.4",
      votersNumber: "16000",
      resolution: "WEB-DL HDR 2160p",
      genres: ["ترسناک", "جنایی", "معمایی", "هیجان انگیز"],
      year: "2021",
      country: ["آمریکا"],
      director: "Darren Lynn Bousman",
      actors: [
        "Chris Rock",
        "Marisol Nichols",
        "Max Minghella",
        "Samuel L. Jackson",
      ],
      ageRate: "R",
      summary:
        "گروهی از کارگاهان و افراد مختلف را به تصویر می کشد که خیلی زود وارد یک بازی مرگبار می شوند، اکنون آنها باید به دنبال راهی برای نجات جان خویش باشند و...",
      imageGallery: ["spiral-1.jpg", "spiral-2.jpg", "spiral-3.jpg"],
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "18 خرداد 1400",
      comments: "14",
    },
    {
      _id: "m2",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "Sentinelle 2021",
      type: "movie",
      imgUrl: "/images/m2.jpg",
      imdbRate: "4.7",
      votersNumber: "6500",
      resolution: "WEB-DL x265 10bit 1080p",
      genres: ["اکشن"],
      year: "2021",
      country: ["فرانسه"],
      director: "Julien Leclercq",
      actors: [
        "Andrey Gorlenko",
        "Blaise Afonso",
        "Gabriel Almaer",
        "Michel Biel",
      ],
      ageRate: "TV-MA",
      summary:
        "کلارای سی و سه ساله، مترجم ارتش فرانسه است. وی پس از تجربه وحشت از جنگ در سوریه، در قالب عملیات سنتینل به نیس منتقل می شود...",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "18 خرداد 1400",
      comments: "",
    },
    {
      _id: "m3",
      specialOffers: ["همراه با نسخه دوبله فارسی"],
      title: "A Writer’s Odyssey 2021",
      type: "movie",
      imgUrl: "/images/m3.jpg",
      imdbRate: "6.3",
      votersNumber: "1100",
      resolution: "WEB-DL 1080p",
      genres: [
        "اکشن",
        "جنایی",
        "درام",
        "علمی و تخیلی",
        "فانتزی",
        "ماجراجویی",
        "معمایی",
        "هیجان انگیز",
      ],
      year: "2021",
      country: ["چین"],
      director: "Yang Lu",
      actors: ["Jiayin Lei", "Jingfei Guo", "Liya Tong", "Zijian Dong"],
      ageRate: "",
      summary:
        "مردی شش سال پس از ربودن دخترش، برای کشتن نویسنده یک رمان فانتزی استخدام می شود، اما به نظر می رسد دنیای رمان با واقعیت تلاقی می کند...",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "18 خرداد 1400",
      comments: "1",
    },
    {
      _id: "m4",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "The Platform 2019",
      type: "movie",
      imgUrl: "/images/m4.jpg",
      imdbRate: "7",
      votersNumber: "177125",
      resolution: "WEB-DL x265 10bit 1080p",
      genres: ["ترسناک", "علمی و تخیلی", "هیجان انگیز"],
      year: "2019",
      country: ["اسپانیا"],
      director: "Galder Gaztelu-Urrutia",
      actors: [
        "Antonia San Juan",
        "Emilio Buale",
        "Ivan Massagué",
        "Zorion Eguileor",
      ],
      ageRate: "TV-MA",
      summary:
        "زندانی عمودی با یک سلول در هر سطح است که دو نفر در هر سلول هستند و تنها یک سکوی غذایی و دو دقیقه در روز برای تغذیه از بالا به پایین ارسال می شود. این کابوسی بی پایان برای به دام افتادگان در گودال است و...",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "7 خرداد 1400",
      comments: "3",
    },
    {
      _id: "m5",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "The Hangover 2009",
      type: "movie",
      imgUrl: "/images/m5.jpg",
      imdbRate: "7.7",
      votersNumber: "707751",
      resolution: "BluRay 10bit x265 1080p",
      genres: ["ترسناک", "علمی و تخیلی", "هیجان انگیز"],
      year: "2009",
      country: ["آلمان", "آمریکا"],
      director: "Todd Phillips",
      actors: [
        "Bradley Cooper",
        "Ed Helms",
        "Justin Bartha",
        "Zach Galifianakis",
      ],
      ageRate: "r",
      summary:
        "این فیلم ماجراهای پیامد یک شب بدمستی سه ساقدوش و یک داماد است در لاس وگاس، دو روز پیش از عروسی. صبح روز بعد وقتی در اطاق نیمه ویران هتل بیدار می شوند یک ببر در حمام است و دندان یکی شکسته و از همه مهم تر، داماد گم شده است و یک ماشین پلیس در پارکینگ هتل به نام آنها پارک شده…",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      trailerLink: "#",
      createAt: "9 آبان 1399",
      comments: "",
    },
    {
      _id: "m4",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "The Platform 2019",
      type: "movie",
      imgUrl: "/images/m4.jpg",
      imdbRate: "7",
      votersNumber: "177125",
      resolution: "WEB-DL x265 10bit 1080p",
      genres: ["ترسناک", "علمی و تخیلی", "هیجان انگیز"],
      year: "2019",
      country: ["اسپانیا"],
      director: "Galder Gaztelu-Urrutia",
      actors: [
        "Antonia San Juan",
        "Emilio Buale",
        "Ivan Massagué",
        "Zorion Eguileor",
      ],
      ageRate: "TV-MA",
      summary:
        "زندانی عمودی با یک سلول در هر سطح است که دو نفر در هر سلول هستند و تنها یک سکوی غذایی و دو دقیقه در روز برای تغذیه از بالا به پایین ارسال می شود. این کابوسی بی پایان برای به دام افتادگان در گودال است و...",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "7 خرداد 1400",
      comments: "3",
    },
    {
      _id: "m1",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "Spiral 2021",
      type: "movie",
      imgUrl: "/images/m1.jpg",
      imdbRate: "5.4",
      votersNumber: "16000",
      resolution: "WEB-DL HDR 2160p",
      genres: ["ترسناک", "جنایی", "معمایی", "هیجان انگیز"],
      year: "2021",
      country: ["آمریکا"],
      director: "Darren Lynn Bousman",
      actors: [
        "Chris Rock",
        "Marisol Nichols",
        "Max Minghella",
        "Samuel L. Jackson",
      ],
      ageRate: "R",
      summary:
        "گروهی از کارگاهان و افراد مختلف را به تصویر می کشد که خیلی زود وارد یک بازی مرگبار می شوند، اکنون آنها باید به دنبال راهی برای نجات جان خویش باشند و...",
      imageGallery: ["spiral-1.jpg", "spiral-2.jpg", "spiral-3.jpg"],
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "18 خرداد 1400",
      comments: "14",
    },
    {
      _id: "m2",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "Sentinelle 2021",
      type: "movie",
      imgUrl: "/images/m2.jpg",
      imdbRate: "4.7",
      votersNumber: "6500",
      resolution: "WEB-DL x265 10bit 1080p",
      genres: ["اکشن"],
      year: "2021",
      country: ["فرانسه"],
      director: "Julien Leclercq",
      actors: [
        "Andrey Gorlenko",
        "Blaise Afonso",
        "Gabriel Almaer",
        "Michel Biel",
      ],
      ageRate: "TV-MA",
      summary:
        "کلارای سی و سه ساله، مترجم ارتش فرانسه است. وی پس از تجربه وحشت از جنگ در سوریه، در قالب عملیات سنتینل به نیس منتقل می شود...",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "18 خرداد 1400",
      comments: "",
    },
    {
      _id: "m3",
      specialOffers: ["همراه با نسخه دوبله فارسی"],
      title: "A Writer’s Odyssey 2021",
      type: "movie",
      imgUrl: "/images/m3.jpg",
      imdbRate: "6.3",
      votersNumber: "1100",
      resolution: "WEB-DL 1080p",
      genres: [
        "اکشن",
        "جنایی",
        "درام",
        "علمی و تخیلی",
        "فانتزی",
        "ماجراجویی",
        "معمایی",
        "هیجان انگیز",
      ],
      year: "2021",
      country: ["چین"],
      director: "Yang Lu",
      actors: ["Jiayin Lei", "Jingfei Guo", "Liya Tong", "Zijian Dong"],
      ageRate: "",
      summary:
        "مردی شش سال پس از ربودن دخترش، برای کشتن نویسنده یک رمان فانتزی استخدام می شود، اما به نظر می رسد دنیای رمان با واقعیت تلاقی می کند...",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "18 خرداد 1400",
      comments: "1",
    },
    {
      _id: "m4",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "The Platform 2019",
      type: "movie",
      imgUrl: "/images/m4.jpg",
      imdbRate: "7",
      votersNumber: "177125",
      resolution: "WEB-DL x265 10bit 1080p",
      genres: ["ترسناک", "علمی و تخیلی", "هیجان انگیز"],
      year: "2019",
      country: ["اسپانیا"],
      director: "Galder Gaztelu-Urrutia",
      actors: [
        "Antonia San Juan",
        "Emilio Buale",
        "Ivan Massagué",
        "Zorion Eguileor",
      ],
      ageRate: "TV-MA",
      summary:
        "زندانی عمودی با یک سلول در هر سطح است که دو نفر در هر سلول هستند و تنها یک سکوی غذایی و دو دقیقه در روز برای تغذیه از بالا به پایین ارسال می شود. این کابوسی بی پایان برای به دام افتادگان در گودال است و...",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "7 خرداد 1400",
      comments: "3",
    },
    {
      _id: "m5",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "The Hangover 2009",
      type: "movie",
      imgUrl: "/images/m5.jpg",
      imdbRate: "7.7",
      votersNumber: "707751",
      resolution: "BluRay 10bit x265 1080p",
      genres: ["ترسناک", "علمی و تخیلی", "هیجان انگیز"],
      year: "2009",
      country: ["آلمان", "آمریکا"],
      director: "Todd Phillips",
      actors: [
        "Bradley Cooper",
        "Ed Helms",
        "Justin Bartha",
        "Zach Galifianakis",
      ],
      ageRate: "r",
      summary:
        "این فیلم ماجراهای پیامد یک شب بدمستی سه ساقدوش و یک داماد است در لاس وگاس، دو روز پیش از عروسی. صبح روز بعد وقتی در اطاق نیمه ویران هتل بیدار می شوند یک ببر در حمام است و دندان یکی شکسته و از همه مهم تر، داماد گم شده است و یک ماشین پلیس در پارکینگ هتل به نام آنها پارک شده…",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      trailerLink: "#",
      createAt: "9 آبان 1399",
      comments: "",
    },
    {
      _id: "m2",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "Sentinelle 2021",
      type: "movie",
      imgUrl: "/images/m2.jpg",
      imdbRate: "4.7",
      votersNumber: "6500",
      resolution: "WEB-DL x265 10bit 1080p",
      genres: ["اکشن"],
      year: "2021",
      country: ["فرانسه"],
      director: "Julien Leclercq",
      actors: [
        "Andrey Gorlenko",
        "Blaise Afonso",
        "Gabriel Almaer",
        "Michel Biel",
      ],
      ageRate: "TV-MA",
      summary:
        "کلارای سی و سه ساله، مترجم ارتش فرانسه است. وی پس از تجربه وحشت از جنگ در سوریه، در قالب عملیات سنتینل به نیس منتقل می شود...",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "18 خرداد 1400",
      comments: "",
    },
    {
      _id: "m3",
      specialOffers: ["همراه با نسخه دوبله فارسی"],
      title: "A Writer’s Odyssey 2021",
      type: "movie",
      imgUrl: "/images/m3.jpg",
      imdbRate: "6.3",
      votersNumber: "1100",
      resolution: "WEB-DL 1080p",
      genres: [
        "اکشن",
        "جنایی",
        "درام",
        "علمی و تخیلی",
        "فانتزی",
        "ماجراجویی",
        "معمایی",
        "هیجان انگیز",
      ],
      year: "2021",
      country: ["چین"],
      director: "Yang Lu",
      actors: ["Jiayin Lei", "Jingfei Guo", "Liya Tong", "Zijian Dong"],
      ageRate: "",
      summary:
        "مردی شش سال پس از ربودن دخترش، برای کشتن نویسنده یک رمان فانتزی استخدام می شود، اما به نظر می رسد دنیای رمان با واقعیت تلاقی می کند...",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "18 خرداد 1400",
      comments: "1",
    },
    {
      _id: "m1",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "Spiral 2021",
      type: "movie",
      imgUrl: "/images/m1.jpg",
      imdbRate: "5.4",
      votersNumber: "16000",
      resolution: "WEB-DL HDR 2160p",
      genres: ["ترسناک", "جنایی", "معمایی", "هیجان انگیز"],
      year: "2021",
      country: ["آمریکا"],
      director: "Darren Lynn Bousman",
      actors: [
        "Chris Rock",
        "Marisol Nichols",
        "Max Minghella",
        "Samuel L. Jackson",
      ],
      ageRate: "R",
      summary:
        "گروهی از کارگاهان و افراد مختلف را به تصویر می کشد که خیلی زود وارد یک بازی مرگبار می شوند، اکنون آنها باید به دنبال راهی برای نجات جان خویش باشند و...",
      imageGallery: ["spiral-1.jpg", "spiral-2.jpg", "spiral-3.jpg"],
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      createAt: "18 خرداد 1400",
      comments: "14",
    },
    {
      _id: "m5",
      specialOffers: ["همراه با نسخه دوبله فارسی", "همراه با زیرنویس چسبیده"],
      title: "The Hangover 2009",
      type: "movie",
      imgUrl: "/images/m5.jpg",
      imdbRate: "7.7",
      votersNumber: "707751",
      resolution: "BluRay 10bit x265 1080p",
      genres: ["ترسناک", "علمی و تخیلی", "هیجان انگیز"],
      year: "2009",
      country: ["آلمان", "آمریکا"],
      director: "Todd Phillips",
      actors: [
        "Bradley Cooper",
        "Ed Helms",
        "Justin Bartha",
        "Zach Galifianakis",
      ],
      ageRate: "r",
      summary:
        "این فیلم ماجراهای پیامد یک شب بدمستی سه ساقدوش و یک داماد است در لاس وگاس، دو روز پیش از عروسی. صبح روز بعد وقتی در اطاق نیمه ویران هتل بیدار می شوند یک ببر در حمام است و دندان یکی شکسته و از همه مهم تر، داماد گم شده است و یک ماشین پلیس در پارکینگ هتل به نام آنها پارک شده…",
      downloadLinks: [
        {
          title: "زبان اصلی",
          linkItems: [
            {
              resolution: "BluRay x265 10bit 1080p",
              format: "mkv",
              encoder: "psa",
              size: "1.9gb",
            },
            {
              resolution: "BluRay 1080p",
              format: "mp4",
              encoder: "yts",
              size: "2.3gb",
            },
            {
              resolution: "BluRay x265 10bit 720p",
              format: "mkv",
              encoder: "psa",
              size: "1.0gb",
            },
          ],
        },
        {
          title: "دوبله فارسی (دو زبانه)",
          linkItems: [
            {
              resolution: "WEB-DL 1080p",
              format: "mkv",
              encoder: "",
              size: "2.4gb",
            },
            {
              resolution: "WEB-DL 720p",
              format: "mkv",
              encoder: "",
              size: "1.4gb",
            },
            {
              resolution: "WEB-DL 480p",
              format: "mkv",
              encoder: "",
              size: "790mb",
            },
          ],
        },
      ],
      relatedMovies: [
        { title: "Hangover", imageUrl: "/images/m5.jpg", imdbRate: "6.2" },
        {
          title: "Millions Dollor Baby",
          imageUrl: "/images/movie2.jpg",
          imdbRate: "7.2",
        },
        { title: "Top Gun", imageUrl: "/images/movie3.jpg", imdbRate: "5.1" },
        {
          title: "The Super Deep",
          imageUrl: "/images/movie4.jpg",
          imdbRate: "3.2",
        },
        { title: "Platform", imageUrl: "/images/m5.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie3.jpg", imdbRate: "8.5" },
        { title: "Platform", imageUrl: "/images/movie2.jpg", imdbRate: "8.5" },
      ],
      trailerLink: "#",
      createAt: "9 آبان 1399",
      comments: "",
    },
  ],
  action
) => {
  switch (action.type) {
    case "SET_MOVIES":
      return [...action.payload];
    case "CLEAR_MOVIES":
      return [...action.payload];
    default:
      return state;
  }
};
